---

- name: Ensure stickiness and migration threshold are configured properly
  command: "{{ item }}"
  loop:
    - pcs resource defaults resource-stickiness=1000
    - pcs resource defaults migration-threshold=5000

- name: Create SAP HANA topology
  shell: |
    pcs resource create SAPHanaTopology_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }} && \
    SAPHanaTopology SID={{ sap_hana_deployment_hana_sid }} InstanceNumber={{ sap_hana_deployment_hana_instance_number }} && \
    op start timeout=600 && \
    op stop timeout=300 && \
    op monitor interval=10 timeout=600 && \
    clone clone-max=2 clone-node-max=1 interleave=true

- name: Create SAP HANA resource agent
  shell: |
    pcs resource create SAPHana_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }} && \
    SAPHana SID={{ sap_hana_deployment_hana_sid }} InstanceNumber={{ sap_hana_deployment_hana_instance_number }} && \
    PREFER_SITE_TAKEOVER=true DUPLICATE_PRIMARY_TIMEOUT=7200 AUTOMATED_REGISTER=true && \
    op start timeout=3600 && \
    op stop timeout=3600 && \
    op monitor interval=61 role="Slave" timeout=700 && \
    op monitor interval=59 role="Master" timeout=700 && \
    op promote timeout=3600 && \
    op demote timeout=3600 && \
    promotable meta notify=true clone-max=2 clone-node-max=1 interleave=true

- name: Create Virtual IP resource
  shell: |
    pcs resource create vip_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }} && \
    IPaddr2 ip="{{ sap-hana-ha-pacemaker-vip }}"

- name: Create Cluster constrains
  shell: |
    pcs constraint order SAPHanaTopology_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }}-clone && \
    then SAPHana_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }}-clone symmetrical=false

- name: Colocate Cluster constrain
  shell: |
    pcs constraint colocation add vip_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }} && \
    with master SAPHana_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }}-clone 2000

- name: Create second Virtual IP resource for Active/Read-Enabled HANA on the secondary node
  shell: |
    pcs resource create vip2_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }} && \
    IPaddr2 ip="{{ sap-hana-ha-pacemaker-secondary-vip }}"
  when:
    - sap-hana-ha-pacemaker-secondary-read

- name: Colocate Cluster constrain for Active/Read-Enabled HANA on the secondary node
  shell: |
    pcs constraint colocation add vip2_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }} && \
    with slave SAPHana_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }}-clone 2000