---
- name: Set fact for repositories to be used depending on the host architecture
  set_fact:
    sap_hana_ha_pacemaker_e4s_repos: "{{ sap_hana_ha_pacemaker_e4s_repos_x86_64 }}"
    sap_hana_ha_pacemaker_standard_repos: "{{ sap_hana_ha_pacemaker_standard_repos_x86_64 }}"
  when: ansible_architecture == "x86_64"

- name: Set fact for repositories to be used depending on the host architecture
  set_fact:
    sap_hana_ha_pacemaker_e4s_repos: "{{ sap_hana_ha_pacemaker_e4s_repos_ppc64le }}"
    sap_hana_ha_pacemaker_standard_repos: "{{ sap_hana_ha_pacemaker_standard_repos_ppc64le }}"
  when: ansible_architecture == "ppc64le"
