---

- name: Ensure cluster and HANA instances are stopped
  pacemaker_cluster:
    state: offline

- name: Ensure '/hana/shared/myHooks' exists
  file:
    path: /hana/shared/myHooks
    state: directory
    mode: '0755'
    owner: "{{ sap_hana_hsr_hana_sid | lower }}adm"
    group: sapsys

- name: Ensure SAPHanaSR hook is copied to the new location
  copy:
    src: /usr/share/SAPHanaSR/srHook/SAPHanaSR.py
    dest: /hana/shared/myHooks/SAPHanaSR.py
    remote_src: yes

- name: Ensure global.ini file is updated
  copy:
    src: "{{ role_path }}/files/global.ini"
    dest: "/hana/shared/{{ sap_hana_hsr_hana_sid }}/global/hdb/custom/config/global.ini"
    force: yes

- name: Ensure sudo configuration is updated
  copy:
    src: "{{ role_path }}/files/20-saphana"
    dest: "/etc/sudoers.d/20-saphana"
    force: yes

- name: Ensure HANA instances are started
  shell: |
      /usr/sap/{{ sap_hana_hsr_hana_sid | upper }}/HDB{{ sap_hana_hsr_hana_instance_number }}/HDB start
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ sap_hana_hsr_hana_sid | lower }}adm"
  register: startinstance
  changed_when: "'StartSystem' in startinstance.stdout"

- name: Ensure cluster is started
  pacemaker_cluster:
    state: online