---

- name: Create cluster user
  user:
    name: {{ sap_hana_ha_pacemaker_user }}
    password: {{ sap_hana_ha_pacemaker_password }}

- name: Enable cluster services
  service: pcsd
  state: started
  service: pcsd
  state: started
  service: corosync
  state: started
  service: pacemaker
  state: started

- name: Grant nodes access to cluster
  command: pcs cluster auth {{ sap_hana_ha_pacemaker_node1 }} {{ sap_hana_ha_pacemaker_node2 }}
    